# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0146_add_portal_tag_models'),
        ('ask_cfpb', '0023_add_portal_links_to_answerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalTopicOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_topics', to='v1.CFGOVPage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='v1.PortalTopic')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='answerpage',
            name='portal_topic',
        ),
        migrations.RemoveField(
            model_name='answerpage',
            name='primary_portal_topic',
        ),
    ]
